services:
  app:
    build: .
    container_name: solvaafrica
    ports:
      - "3002:3002"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    depends_on:
      redis:
        condition: service_healthy
      mysql:
        condition: service_healthy
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: solva
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - mysql-data:/var/lib/mysql
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

volumes:
  mysql-data:
